apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpersistentvolume1
spec:
  storageClassName: storageosdemoclass1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi